### ISSUE TITLE
tag a release? 

### ISSUE THREAD

**Issue by jrobeson** [PocketRent/hhvm-pgsql#44]
There hasn't been a release since PDO support was added. Do you think it's ready now?

**Comment by rybakit** [comment]
:+1:  
Add please add a new pre-built version to the "releases" branch to ease installing it on Travis.

**Comment by bountin** [comment]
@rybakit Do you have any reading material how to install hhvm extensions at travis? I'd like to add hhvm-pgsql to Doctrine's travis instance and haven't found any resources on this yet.

**Comment by jrobeson** [comment]
you apt-get install hhvm-dev and then follow the instructions on the README

**Comment by rybakit** [comment]
@jrobeson As Travis CI is based on Ubuntu 12.04 it's quite tricky to make it working, because you have to recomplie all third-party libraries to the newer versions: https://github.com/facebook/hhvm/wiki/building-and-installing-hhvm-on-ubuntu-12.04#building-third-party-libraries. 

@bountin I gave up to to install hhvm-pgsql for my library after a number of unsuccessful attempts. You can check my [.travis.yml](https://github.com/rybakit/phive-queue/blob/77aeef4f7be31137a24e60a584a4b47ecc7e5031/.travis.yml) file for further investigations if you interest.

**Comment by simonwelsh** [comment]
Tagged 3.6.0.

**Comment by rybakit** [comment]
Tried to use complied pgsql.so with HipHop VM 3.6.0-dev on Travis, but got this: 
```
Uncaught exception: Could not load extension .../pgsql.so: getModuleBuildInfo() symbol not defined.
```
Any idea how to fix this?

**Comment by simonwelsh** [comment]
Wait for 3.6.0 stable. The change that added `getModuleBuildInfo` to HHVM won't be included in it.
