### ISSUE TITLE
Improperly escaped BYTEA insertions

### ISSUE THREAD

**Issue by michaelmarlow** [PocketRent/hhvm-pgsql#46]
Using Symfony/Doctrine with this extension to insert into a BYTEA field returns the error below. Improper hex escaping syntax is being used. Same setup works fine with php5-fpm and standard pdo_pgsql driver, but fails here on hhvm with this extension.

[2015-01-03 16:02:14] request.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "\" LINE 1: UPDATE session SET session_value = \x5f7366325f6174747269627...                                            ^ " at  line  {"exception":"[object] (PDOException(code: 42601): SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"\\\"\nLINE 1: UPDATE session SET session_value = \\x5f7366325f6174747269627...\n                                           ^\n at :)"} []

**Comment by mzaslavsky** [comment]
If your program uses PHP's Large Objects (LOB) this library appears to have a bug since it doesn't add single quotes around the escaped BYTEA field in pdo_pgsql_connection.cpp:

    bool PDOPgSqlConnection::quoter(const String& input, String &quoted, PDOParamType paramtype){
        switch(paramtype){
            case PDO_PARAM_LOB:
                quoted = m_conn->escapeByteA(input.data(), input.length());
                return true;
                break;

...but it does add them for the default PDOParamType.

As an aside, I experience the same issue in Drupal 7 (pgsql v.9.2, HHVM 3.5 - using commit from more than 3 days ago since newer commits apparently only work for > HHVM3.6?).

One example (where "..." below indicates an extended hex sequence"):
2015-02-25 20:54:16 AEDT ERROR:  syntax error at or near "\" at character 83
2015-02-25 20:54:16 AEDT STATEMENT:  UPDATE cache_bootstrap SET serialized='1', created='1424858056', expire='0', data=\x613a...65223b7d7d
	WHERE ( (cid = 'bootstrap_modules') )

Drupal uses a large object stream (PDO::PARAM_LOB) for BYTEA columns in its pgsql driver:
          $blobs[$blob_count] = fopen('php://memory', 'a');
          fwrite($blobs[$blob_count], $insert_values[$idx]);
          rewind($blobs[$blob_count]);

          $stmt->bindParam(':db_insert_placeholder_' . $max_placeholder++, $blobs[$blob_count], PDO::PARAM_LOB);

Unfortunately I barely know C++ whatsoever so I can't provide a patch (let alone handle all the memory management issues). I assume concatenation would be something along the lines of:

bool PDOPgSqlConnection::quoter(const String& input, String &quoted, PDOParamType paramtype){
        std::string escaped_lob;
        std::string quoted_escaped_lob;
        switch(paramtype){
            case PDO_PARAM_LOB:
		escaped_lob = m_conn->escapeByteA(input.data(), input.length());
		quoted_escaped_lob = "\'" + escaped_lob + "\'\0";
                quoted = String(quoted_escaped_lob, CopyString);
                return true;
                break;

Handling of large objects is also incomplete in this extension so I suppose you could run into other issues if your program relies on it extensively.

**Comment by Kazanir** [comment]
Because `escapeByteA()` conveniently returns a string and `&quoted` is provided by the caller, we should just be able to add this:

```
quoted = m_conn->escapeByteA(input.data(), input.length());
quoted = "'" + quoted + "'";
```

Because this is literally the first line of C++ I've ever written I'm open to being corrected. It compiled and seemed to work fine for us today, though. :)

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
