### ISSUE TITLE
PDO vs pg_fetch_* results mismatch

### ISSUE THREAD

**Issue by Kazanir** [PocketRent/hhvm-pgsql#77]
Drupal does some database settings checking as part of its install process, and it fails a check when using this lib, specifically checking that `SELECT 'encoding'::bytea` is set to "encoding". PDO returns a NULL for this query while `pg_fetch_*` functions seem to return the correct value:

```
$db = new PDO($dsn, 'user', 'pass');
var_dump($db->query("SELECT 'encoding'::bytea AS output;")->fetch(PDO::FETCH_OBJ)); 
// object(stdClass) (1) { ["output"] => NULL }

$conn = pg_connect($dsn);
$result = pg_query($conn, "SELECT 'encoding'::bytea AS output;");
var_dump(pg_fetch_object($result)); 
// object(stdClass) (1) { ["output"] => string(8) "encoding" }
```

Seems like something is amiss, here!

**Comment by javacty** [comment]
I have the same problem .

**Comment by mzaslavsky** [comment]
I've abandoned hhvm with pgsql for running Drupal 7 since I previously encountered the shortcomings of this plug-in having no Large Object streaming support (https://github.com/PocketRent/hhvm-pgsql/issues/46). For years I've had to work around several (yet unresolved) Drupal bugs as well just to get Postgres to work reliably (namely, restricting index name length) so its lack of popularity compared with mySQL might keep it back for many years to come.

**Comment by d0dge** [comment]
Same issue still .  My use case is the same, trying to install Drupal.

With HHVM 3.9, the PDO returns NULL for the above-mentioned query, so the installer cannot continue.

With HHVM 3.10.0, HHVM actually crashes without error at the same point, obviously also bringing the install to a halt.

**Comment by simonwelsh** [comment]
Hi,

With the release of HHVM 3.15, hhvm-pgsql is now include in as port of the core repository. If you are still experiencing this issue, please create an issue in the [facebook/hhvm](https://github.com/facebook/hhvm/issues) repository.
